version: '3'

tasks:
  pip:
    cmds:
      - python3 -m venv venv
      - pip install -r requirements.txt

  lint:
    cmds:
      - prettier --write .

  venv:
    cmds:
      - source venv/bin/activate

  export:
    cmds:
      - pip freeze > requirements.txt

  dev:
    cmds:
      - python cmd/main.py
