version: '3'

tasks:

  venv:
    cmds:
      - rm -rf ./venv
      - python3 -m venv venv
      - source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

  export:
    cmds:
      - source venv/bin/activate && pip freeze > requirements.txt

  lint:
    cmds:
      - source venv/bin/activate && flake8 .

  dev:
    cmds:
      - source venv/bin/activate && fastapi dev cmd/main.py
