version: '3'

tasks:

  init:
    cmds:
      - rm -rf ./venv
      - python3 -m venv venv
      - echo 'export PYTHONPATH=$(pwd)' >> venv/bin/activate
      - |
        source venv/bin/activate &&
        pip install --upgrade pip &&
        pip install -r requirements.txt

  export:
    cmds:
      - |
        source venv/bin/activate &&
        pip freeze > requirements.txt

  lint:
    cmds:
      - |
        source venv/bin/activate &&
        black .

  dev:
    cmds:
      - |
        source venv/bin/activate &&
        fastapi dev cmd/main.py

  main:
    cmds:
      - |
        source venv/bin/activate &&
        python cmd/main.py
